// Generated by CoffeeScript 1.3.3
(function() {

  window.addEventListener("load", function() {
    return Q.Sprite.extend("Player", function() {
      return {
        teste: function() {
          return console.log("wtf");
        },
        init: function(p) {
          console.log("Player!");
          this._super(p, {
            sheet: "player",
            x: 410,
            y: 90
          });
          return this.add("2d, platformerControls");
        }
      };
    });
  });

}).call(this);
